server:
  port: 8080
spring:
  application:
    name: basic-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.101.88:3306/micro_learning_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: pan19991209
    hikari:
      auto-commit: true
      pool-name: MyHikariCP
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 90000
      connection-timeout: 10000
      connection-test-query: SELECT 1
#  cloud:
#    nacos:
#      server-addr: localhost:8848 # nacos服务地址
#      discovery:
#        cluster-name: Chengdu #集群名称 定义为成都
#        namespace: 85e8b316-f734-4bb7-9fb9-82f0fd3ac685 #命名空间 配置需要选择ID,非同一个命名空间无法远程调用
#        ephemeral: false # false为非临时示例 由Nacos主动维护服务是否健康；true为临时实例，由服务自己向Nacos发送心跳。
#        # Current service DEFAULT_GROUP@@basic-user is ephemeral service, can't register persistent instance.可通过切换组或者删除\data\protocol\raft的配置
#        group: DEFAULT_GROUP #永久实例组
#eureka:
#  client:
#    service-url: # Eureka服务地址
#      defaultZone: http://127.0.0.1:12999/eureka
logging:
  level:
    org.example: debug